version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # Add any pre-build tasks here

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py

  pre_unit_test:
    commands:
      - echo "Running pre-unit tests..."
      # Add any pre-unit testing tasks here

  unit_test:
    commands:
      - echo "Running unit tests..."
      - python -m unittest discover tests/unit

  post_unit_test:
    commands:
      - echo "Running post-unit tests..."
      # Add any post-unit testing tasks here

  integration_test:
    commands:
      - echo "Running integration tests..."
      # Add integration testing commands here

  post_integration_test:
    commands:
      - echo "Running post-integration tests..."
      # Add any post-integration testing tasks here

  e2e_test:
    commands:
      - echo "Running end-to-end tests..."
      # Add end-to-end testing commands here

  post_e2e_test:
    commands:
      - echo "Running post end-to-end tests..."
      # Add any post end-to-end testing tasks here

  security_scan:
    commands:
      - echo "Running security scans..."
      # Add security scanning commands (e.g., SAST)

  post_security_scan:
    commands:
      - echo "Running post-security scan checks..."
      # Add post-security scan checks (e.g., dependency vulnerability checks)

  post_build:
    commands:
      - echo "Running post-build tasks..."
      # Add any post-build tasks, including deployment
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name githubtolambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

artifacts:
  files: deployment_package.zip
