version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Creating deployment package directory..."
      - mkdir -p deployment_package/
      - echo "Copying test.csv to deployment package..."
      - set -x  # Enable debugging output
      - aws s3 cp s3://satwinder/test.csv deployment_package/ || echo "Failed to copy file."
      - set +x  # Disable debugging output
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip deployment_package/

      # Additional build steps
      - echo "Running unit tests..."
      - python -m unittest discover tests/ -v

  post_build:
    commands:
      - echo "Updating Lambda Function..."
      - set -x  # Enable debugging output
      - aws lambda update-function-code --function-name githubtolambda --zip-file fileb://deployment_package.zip
      - set +x  # Disable debugging output
      - echo "DONE!!"
