version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      
      # Add the S3 upload step here
      - echo "Uploading test.csv file to S3..."
      - aws s3 cp path/to/your/local/test.csv s3://your_bucket_name/your_test_file.csv  # Replace with the actual path to your local test.csv file
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name githubtolambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
